#!/usr/bin/env bash

if ! [ -x "$(command -v brew)" ]; then
  echo 'Error: Install Homebrew from https://brew.sh/#install' >&2
  exit 1
fi

### Make all symlinks ###

# FISH SHELL #
mkdir ~/.config
ln -s "$(pwd)/fish-shell" ~/.config/fish

# VSCODE #
mkdir -p ~/Library/Application\ Support/Code/User/
ln -s "$(pwd)/vscode/settings.json" ~/Library/Application\ Support/Code/User

### Install All Apps ##
brew bundle
