tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "fish"
brew "git"
brew "httpie"
brew "lsd"
brew "mas"
cask "alfred"
cask "font-source-code-pro"
cask "iterm2"
cask "slack"
cask "spotify"
cask "tableplus"
cask "typora"
cask "visual-studio-code"
mas "Dato", id: 1470584107
